resource_registry:
  OS::TripleO::Services::CephMon: /usr/share/openstack-tripleo-heat-templates/docker/services/ceph-ansible/ceph-mon.yaml
  OS::TripleO::Services::CephOSD: /usr/share/openstack-tripleo-heat-templates/docker/services/ceph-ansible/ceph-osd.yaml
  OS::TripleO::Services::CephClient: /usr/share/openstack-tripleo-heat-templates/docker/services/ceph-ansible/ceph-client.yaml

parameter_defaults:
  CephAnsiblePlaybookVerbosity: 1
  CinderEnableIscsiBackend: false
  CinderEnableRbdBackend: true
  CinderBackupBackend: ceph
  NovaEnableRbdBackend: true
  GlanceBackend: rbd
  GnocchiBackend: rbd

  CephPoolDefaultPgNum: 128
  CephConfigOverrides:
    #bluestore block db size: 67108864
    #bluestore block wal size: 134217728
    journal_size: 5120
    #max_open_files: 131072
    mon_max_pg_per_osd: 3072
    #mon_osd_full_ratio: 90
    #osd_max_backfills: 1
    osd_pool_default_size: 3
    osd_pool_default_min_size: 2
    osd_pool_default_pg_num: 128
    osd_pool_default_pgp_num: 128
    #osd_recovery_op_priority: 3
    #osd_recovery_max_active: 3

  #CephPools:
   # - {"name": .rgw.root, "pg_num": 16, "pgp_num": 16, "application": rados}
   # - {"name": default.rgw.control, "pg_num": 16, "pgp_num": 16, "application": rados}
   # - {"name": default.rgw.meta, "pg_num": 16, "pgp_num": 16, "application": rados}
   # - {"name": default.rgw.log, "pg_num": 16, "pgp_num": 16, "application": rados}
   # - {"name": backups, "pg_num": 16, "pgp_num": 16, "application": rbd}
   # - {"name": images, "pg_num": 128, "pgp_num": 128, "application": rbd}
   # - {"name": metrics, "pg_num": 16, "pgp_num": 16, "application":openstack_gnocchi}
   # - {"name": vms, "pg_num": 512, "pgp_num": 512, "application": rbd}
   # - {"name": volumes, "pg_num": 256, "pgp_num": 256, "application": rbd}  #

  #Filestore
  CephAnsibleDisksConfig:
    devices:
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
      - /dev/sde
      - /dev/sdf
      - /dev/sdg
      - /dev/sdh
      - /dev/sdi
    dedicated_devices:
      - /dev/sdj
      - /dev/sdj
      - /dev/sdj
      - /dev/sdj
      - /dev/sdk
      - /dev/sdk
      - /dev/sdk
      - /dev/sdk
    osd_scenario: non-collocated
  
  #BlueStore
  #CephAnsibleDisksConfig:
  #  devices:
  #    - /dev/sdb
  #    - /dev/sdc
  #    - /dev/sdd
  #    - /dev/sde
  #    - /dev/sdf
  #    - /dev/sdg
  #    - /dev/sdh
  #    - /dev/sdi
  #    - /dev/sdj
  #    - /dev/sdk
  #  osd_scenario: lvm
  #  osd_objectstore: bluestore

  # HCI specific stuff below
  CephAnsibleExtraConfig:
    ceph_osd_docker_memory_limit: 3g
    ceph_osd_docker_cpu_limit: 1
    is_hci: true
